
export enum EBenefitType {
  ITEM_FREE = 'ITEM_FREE',
  PERCENTAGE_OFF = 'PERCENTAGE_OFF',
  AMOUNT_OFF = 'AMOUNT_OFF',
  FIXED_PRICE = 'FIXED_PRICE',
  COUPONB = 'COUPONB',
  GIFT = 'GIFT',
  POINTS = 'POINTS'
}
